name: food_driver
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  collection: ^1.18.0

  # Core
  injectable: ^2.4.2
  get_it: ^7.7.0
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4

  # Network
  dio: ^5.5.0
  talker_dio_logger: ^4.4.1
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1
  signalr_netcore: ^1.3.9

  # Services
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  shared_preferences: ^2.2.3
  webview_flutter: ^4.8.0
  vibration: ^2.0.0
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_pdfview: ^1.3.2
  easy_localization: ^3.0.7
  
  # UI
  # pinput: ^5.0.0
  flutter_native_splash: ^2.4.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  flutter_svg: ^2.0.10+1

flutter:

  uses-material-design: true
  assets:
    - assets/
    - resources/langs/

flutter_native_splash:
  image: assets/splash.png
  color: "#ffffff"
  android_screen_orientation: portrait
